# Generated by Django 3.2.5 on 2021-08-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Produit', 'verbose_name_plural': '3. Produits'},
        ),
    ]
