# Generated by Django 3.2.5 on 2021-08-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('id',), 'verbose_name': 'Sous Catégorie', 'verbose_name_plural': '2. Sous Catégorie'},
        ),
    ]
