# Generated by Django 3.2.5 on 2021-08-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_subcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
    ]
