# Generated by Django 3.2.5 on 2021-08-03 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atributes', '0001_initial'),
        ('core', '0009_auto_20210803_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='atributes.collection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='couleur',
            field=models.ManyToManyField(blank=True, related_name='couleur', to='atributes.Couleur'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pointure',
            field=models.ManyToManyField(blank=True, related_name='pointure', to='atributes.Pointure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='taille',
            field=models.ManyToManyField(blank=True, related_name='tailles', to='atributes.Taille'),
        ),
    ]
