# Generated by Django 3.2.5 on 2021-08-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210803_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_slide', models.ImageField(upload_to='images/slides')),
                ('actif', models.BooleanField(default=False, verbose_name='Active')),
                ('is_big', models.BooleanField(default=False, verbose_name='Grande photo (1920 x 570)')),
                ('is_small', models.BooleanField(default=False, verbose_name='Medium photo (720 x 540)')),
            ],
        ),
    ]
