# Generated by Django 3.2.5 on 2021-08-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='big_slide',
            field=models.ImageField(upload_to='images/slides', verbose_name='URL image '),
        ),
    ]
